version: '3.9'
services:
  elk:
    image: sebp/elk
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d
      - ./logstash/tls/certs:/etc/pki/tls/certs
      - ./logstash/tls/private:/etc/pki/tls/private
      - ./elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - ./elk-data:/var/lib/elasticsearch
    environment:
      - 'TZ=Etc/UTC'
      #- 'ES_HEAP_SIZE=2g'
      #- 'LS_HEAP_SIZE=1g'
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.1
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logstash/tls/certs/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
      - /var/log:/tmp/log
    ports:
      - 9996:9996/udp
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/kibana.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpasswd.users:/etc/nginx/htpasswd.users
    ports:
      - 8080:80
volumes:
  elk-data:
